name: Build and Deploy Web Demo
on:
  push:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Prepare java
      uses: actions/setup-java@v3.5.1
      with:
        distribution: 'zulu'
        java-version: '11'

    - uses: actions/checkout@v3.1.0
    - name: Setup Node
      uses: actions/setup-node@v3.5.0
      with:
        node-version: '17.4.0'

    - name: Install node dependencies
      run: npm install

    - name: Setup Clojure
      # You may pin to the exact commit or the version.
      # uses: DeLaGuardo/setup-clojure@5042876523f30f5efcf1d6feaa48bd1498d7814f
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        # Clojure CLI version to make available on the path.
        cli: 1.10.3.1058

    - name: Install dependencies
      run: clojure -P
    - name: Build static
      run: clojure -M:shadow-cljs:cljs release app
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4.4.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: public # The folder the action should deploy.

